apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fpm
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: fpm
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 30
